"""Build a standalone static mirror of the dashboard.

Copies website/ to a dist dir and overwrites data/*.json with a real snapshot
of live validator state. Payloads come from the affine-dash readers, so they
match what /api/v1 serves; the frontend then runs in the "static" mode api.js
already falls back to when /api/v1/health is absent.

Build outside the repo: the bundle's data/ is read-only published JSON, but
under a gitignored path Ample's deploy advisor reads it as runtime-written
state and demands a volume.

    python -m scripts.build_static_site --out ~/affine-site
    cd ~/affine-site && ample deploy . --kind static --public --runtime static
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
from pathlib import Path

from affine.config import load_config
from affine.dash.readers import contract_payload, snapshot
from affine.dash.tmc import enrich_snapshot, reg_history_for_api

log = logging.getLogger("affine.build_static_site")

AFFINE_DIR = Path(__file__).resolve().parents[1]
SITE_DIR = AFFINE_DIR / "website"

# The validator publishes these to Hippius data/<name> verbatim; state/public
# holds the same bytes. Left as a copy so the mirror can't drift from them.
COPIED = ("history.json", "benchmarks.json")

# Never ship a stale placeholder if the live source is missing.
REQUIRED = ("dashboard.json", "history.json", "contract.json")

# Written into the bundle because the build wipes the output directory.
# `--runtime static` is not optional: code/ carries a pyproject.toml, so the
# source probe otherwise types the whole bundle as Python and fails the deploy
# asking for a start command. Detection also has no way to be told that code/
# is served rather than run, which is why this is a deploy flag and not `ample up`.
AMPLE_TOML = """\
# Generated by affine/scripts/build_static_site.py — edit that, not this.
version = 1

[services.site]
path = "."
kind = "static"
public = true
"""


def build(out_dir: Path) -> None:
    cfg = load_config()
    if out_dir.exists():
        shutil.rmtree(out_dir)
    shutil.copytree(SITE_DIR, out_dir)

    data_dir = out_dir / "data"
    data_dir.mkdir(exist_ok=True)
    for stale in data_dir.glob("*.json"):
        stale.unlink()

    derived = {
        "dashboard.json": enrich_snapshot(cfg, snapshot(cfg)),
        "contract.json": contract_payload(cfg),
        "reg_history.json": reg_history_for_api(cfg),
    }
    for name, payload in derived.items():
        if payload is None:
            log.warning("no live payload for %s — omitting", name)
            continue
        (data_dir / name).write_text(json.dumps(payload))

    public = cfg.state_dir / "public"
    for name in COPIED:
        src = public / name
        if not src.exists():
            log.warning("missing %s — omitting", src)
            continue
        shutil.copyfile(src, data_dir / name)

    missing = [n for n in REQUIRED if not (data_dir / n).exists()]
    if missing:
        raise SystemExit(f"refusing to publish without live {', '.join(missing)}")

    (out_dir / "ample.toml").write_text(AMPLE_TOML)

    snap = derived["dashboard.json"]
    log.info("built %s — generated_at=%s king=%s", out_dir,
             snap.get("generated_at"), (snap.get("king") or {}).get("repo"))


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="~/affine-site",
                    help="output directory (relative paths resolve under affine/)")
    args = ap.parse_args()
    out = Path(args.out).expanduser()
    build(out if out.is_absolute() else AFFINE_DIR / out)


if __name__ == "__main__":
    main()
